### ISSUE TITLE
Module input/output specification

### ISSUE THREAD

**Issue by joetsui1994** [kraemer-lab/GRAPEVNE#122]
One of the things that I struggled with when building DenguePL is making sure that the filename of the input files going into one module match those of the output files from the previous module. When I frequently end up doing is exposing both input/output filenames as parameters, and then making sure they match in the interface in GRAPEVNE.

I am wondering if this is a good practice, and also if these parameters should be displayed separately from other parameters in the panel, so that it is always clear what input files are going into one module and how they are labelled, and what output files are coming out and how they are labelled? Having some sort of visual indicator that these things match when building the DAG might also be helpful.

**Comment by jsbrittain** [comment]
> One of the things that I struggled with when building DenguePL is making sure that the filename of the input files going into one module match those of the output files from the previous module. When I frequently end up doing is exposing both input/output filenames as parameters, and then making sure they match in the interface in GRAPEVNE. I am wondering if this is a good practice, and also if these parameters should be displayed separately from other parameters in the panel, so that it is always clear what input files are going into one module and how they are labelled, and what output files are coming out and how they are labelled?

I think this needs to be a design consideration. At present we link namespaces (folders), not 'files', so there is no restriction to have both input and output files named. However, it is often easier to do so for the reasons that you state. I don't think this is bad practice, but we may be able to provide a more convenient solution. For instance, we could provide special designations on parameters that allow them to be matched by grapevne in the editor. Linked to this, there are very few restrictions on how you can specify your parameters in the configuration file (you don't even have to use the 'config' label if you don't want to), so they could be easily separated out in the config and editor. At some point I would like to clean up the interface to hide namespace and snakefile information by default, thus emphasising these user-defined parameter sets.

This also highlights that we have a very flexible approach to our modules and configurations, but to make the most of our interface we should consider providing stronger guidelines on how to construct modules (in terms of their user-facing properties, separate from how we 'build' the modules themselves. The former point should be incorporated into our early training materials.

> Having some sort of visual indicator that these things match when building the DAG might also be helpful.

The validation button should do this! i.e. check that the dependencies for a module are being met. Visual checks can be turned on automatically in Settings. These checks used to run quite slowly (hence the need to validate manually, but there have been quite a few optimisations later that should make the auto-validate option feasible now).

**Comment by jsbrittain** [comment]
We need to consider two forms of linkage:
1. filename linkage; this is most similar to that discussed above where input and output filenames are parameterised and can be checked at build-time using the 'validate' button. This also allows the possibility of marking these parameters for a new form of 'dynamic linking' within grapevne, e.g. parameter names could be specified as '@filename: data.csv' instead of 'filename: data.csv' (or similar), indicating that grapevne should map these parameters together [where possible] between the two modules. Linked parameters could also potentially be dictionaries of values. One issue arrises as to whether the input (or output) module inherits from the other; or we simply check whether the values match and report to the user if they do not (this degenerates into a solution very much like our existing 'validate' button).
2. data dependent rules; when files or folders are parsed and dependencies rely on input structures to determine outputs. A suggestion here was to specify a glob-style output format that could be matched to an input filename or glob input pattern. operation of the validate button is unclear here since data-dependencies will be drawn from files present in the modules' repository, which have been (up until now) used to store 'test' results for unit tests, etc, and are not copied during the build process.

**Comment by jsbrittain** [comment]
Idea: Include a 'connector' element that allows the user to specify (eventually in a graphical drag-and-drop side-pane) connections between the 'parameters' of the two modules. Having one set of connectors per pair of modules permits flexibility when multiple inputs are provided to a node. Interface within the node editor may look something like this (example is for deleting a connection, but imagine 'x' replaced with another symbol). This system may be reusable between nodes if 'clusters' of parameters can be mapped from one module to another (this would presumably be necessary due to submodule structures anyway).
<img width="229" alt="Screenshot 2023-11-13 at 11 38 36" src="https://github.com/kraemer-lab/GRAPEVNE/assets/98161205/54c7631c-6f4d-49e5-a10c-aac0fb80cda0">

**Comment by jsbrittain** [comment]
Related to above, parameter mapping could be implemented in the workflow `Snakefile`. Workflow files are built by referencing modules (that are usually downloaded from github), with their configurations passed through as, e.g. `config["module2"]`. In order to map parameters from one module to another (e.g. `module1-outfile` to `module2-infile`) we can insert a line of code (remembering that Snakefile's are python script) after the `configfile` directive to force this mapping, i.e. `config['module2']['params']['infile'] = config['module1']['params']['outfile']`. This will associate the value without changing the key. Within a broader context this would be inserted programmatically either at Snakefile-build time, or by referencing special `mapping` elements of the configuration yaml (latter may be prefered as this could naturally extend throughout the hierarchy). It also maintains Snakemake-compatible workflows/mappings, without the need for additional input from grapevne (after the initial build).

**Comment by jsbrittain** [comment]
Additionally, parameter loading from file (which would enable the use of customisable config files) could be added just above the config remapping code. The filenames for these parameter files could also be encoded in the config yaml file, allowing the files to be loaded at run-time.
