### ISSUE TITLE
Error with TEST BUILD (running latest release from Finder)

### ISSUE THREAD

**Issue by joetsui1994** [kraemer-lab/GRAPEVNE#158]
I got the follow error when running TEST BUILD with only the (TutorialBuilder) Download module, after having started GRAPEVNE from Finder by just doubling click the app icon:

I got the following error from the terminal when running TEST BUILD with only the (TutorialBuilder) Download module:

```
Building workflow and launching a test run
Building workflow.
Running workflow.
zsh:1: no such file or directory: /private/var/folders/q9/0h40wky j479vh8zt8z0yssm0000gp/T/Apr
```

<img width="1289" alt="Screenshot 2023-11-08 at 10 05 18" src="https://github.com/kraemer-lab/GRAPEVNE/assets/34651685/6e1dfd0a-bedd-4724-9d9a-d168f518d2ff">

I am running the latest version of GRAPEVNE (uploaded 4 Nov), on an Apple M2 MacbookPro, Ventura 13.5.

**Comment by jsbrittain** [comment]
I've managed to recreate this issue by following the same steps as #157 , namely by renaming the downloaded file 'GRAPEVNE 2' instead of 'GRAPEVNE'. I'll need to look further into exactly why this causes such problems, but in the meantime you can resolve the issue by deleting all GRAPEVNE's in your downloads folder and just downloading the one version and running it (in a folder called 'GRAPEVNE.app').
