### ISSUE TITLE
[BUG]: ERROR 403: rate limit exceeded

### ISSUE THREAD

**Issue by joetsui1994** [kraemer-lab/GRAPEVNE#205]
**Describe the bug**
Getting the message "ERROR 403: rate limit exceeded" from GET MODULE LIST, after only 3-4 requests.

**To Reproduce**
Click "GET MODULE LIST" a few times in the GRAPEVNE interface. This only happens when using certain wifi, as observed before.

**Expected behavior**
N/A

**Screenshots**
<img width="800" alt="Screenshot 2024-02-16 at 11 28 39" src="https://github.com/kraemer-lab/GRAPEVNE/assets/34651685/8cec1fac-5e97-4734-8cc7-0efcc81d9cf5">

**Environment (please complete the following information):**

- Operating System: MacOS Ventura 13.5
- Processor / chip: M2
- GRAPEVNE version: Version 0.2.1 (0.2.1)

**Comment by jsbrittain** [comment]
For context, this is a response from the github api to our request for the repository listing. Since we are not logged in to github whe we make this request (through the grapevne app), the rate limit is severely hobbled ([see here](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28)):
- The primary rate limit for unauthenticated requests is 60 requests per hour.
- The authenticated personal rate limit is 5,000 requests per hour (raising to 15,000 for enterprise, etc.)

This leaves two viable options:
1. Provide a facility to enter github authentication information into grapevne
2. Provide a secondary route to acquire the respository listing (possibly as a failsafe mechanism)

**Comment by jsbrittain** [comment]
Since the github API is only used to return the folder structure of a repository (files are download using `raw.githubusercontent.com`), an alternative suggestion is to maintain a cache of modules on a separate branch / AWS-S3 bucket, etc. This file could parse a list of _known_ repositories. While this is a reasonable workaround, it is not a fix as it would not cover non-listed repos.

**Comment by jsbrittain** [comment]
#287 adds manifest support - GRAPEVNE will first look for a `manifest.json` file (essentially a file-map of the repository); if found it will download and continue to use this file for folder queries (e.g. when probing for multiple configuration files). Automatic manifest creation can be accomplished by CI (github actions) running on the target repository. I will make these available once they are fully automated.
